import {
  classifyUserText,
  groupAssistantWork,
  hasAssistantWork,
  injectionsOf,
  projectDialogue,
  projectExchanges,
  summarizeTool,
  summarizeWork,
  textsOf,
  toolsOf
} from '../src/renderer/src/lib/dialogue.ts'
import type { Message } from '@agentdock/core'

const messages: Message[] = [
  {
    id: 's1',
    conversationId: 'c',
    seq: 0,
    role: 'system',
    createdAt: 1,
    parts: [{ kind: 'text', text: 'token_count input=1 cached=0 output=2 reasoning=0 total=3' }]
  },
  {
    id: 'u1',
    conversationId: 'c',
    seq: 1,
    role: 'user',
    createdAt: 2,
    parts: [{ kind: 'text', text: '添加 operateTypeList' }]
  },
  {
    id: 'a1',
    conversationId: 'c',
    seq: 2,
    role: 'assistant',
    createdAt: 3,
    parts: [{ kind: 'tool_call', name: 'Bash', callId: 't1', input: { command: 'git show 64a3b8', description: 'Show diff' } }]
  },
  {
    id: 't1',
    conversationId: 'c',
    seq: 3,
    role: 'tool',
    createdAt: 4,
    parts: [{ kind: 'tool_result', callId: 't1', output: 'diff --git a/x' }]
  },
  {
    id: 'a2',
    conversationId: 'c',
    seq: 4,
    role: 'assistant',
    createdAt: 5,
    parts: [{ kind: 'text', text: 'Found it. 开始改函数。' }]
  }
]

const items = projectDialogue(messages)
const turns = items.filter((item) => item.kind === 'turn')
if (turns.length !== 2) {
  throw new Error(`expected 2 turns, got ${turns.length}`)
}
const user = turns[0]
const assistant = turns[1]
if (user?.kind !== 'turn' || user.role !== 'user' || textsOf(user)[0] !== '添加 operateTypeList') {
  throw new Error('user turn mismatch')
}
if (assistant?.kind !== 'turn' || assistant.role !== 'assistant') {
  throw new Error('assistant turn missing')
}
if (textsOf(assistant).join('') !== 'Found it. 开始改函数。') {
  throw new Error(`assistant text mismatch: ${textsOf(assistant).join('|')}`)
}
const tools = toolsOf(assistant)
if (tools.length !== 1 || tools[0]?.name !== 'Bash') {
  throw new Error('tool not merged into assistant turn')
}
if (tools[0]?.output !== 'diff --git a/x') {
  throw new Error('tool result not attached')
}
if (assistant.blocks[0]?.kind !== 'tool' || assistant.blocks[1]?.kind !== 'text') {
  throw new Error('blocks should keep tool-then-text order')
}

const summary = summarizeTool('Read', { file_path: '/a/b/pages.ts' })
if (summary !== 'b/pages.ts' && summary !== 'pages.ts' && !summary.includes('pages.ts')) {
  throw new Error(`bad read summary: ${summary}`)
}

const thread = projectExchanges(items)
if (thread.length !== 1 || thread[0]?.kind !== 'exchange') {
  throw new Error(`expected 1 exchange, got ${thread.length}`)
}
const exchange = thread[0]
if (exchange.work.probes.length !== 1 || exchange.work.probes[0]?.tools[0]?.name !== 'Bash') {
  throw new Error('exchange should wrap bash as one probe')
}
if (exchange.work.reply.join('') !== 'Found it. 开始改函数。') {
  throw new Error(`reply mismatch: ${exchange.work.reply.join('|')}`)
}

const grouped = groupAssistantWork([
  { kind: 'text', text: '正在核验两处问题。' },
  { kind: 'tool', tool: { name: 'Grep', summary: 'foo', input: {}, diffs: [] } },
  { kind: 'tool', tool: { name: 'Read', summary: 'a.ts', input: {}, diffs: [] } },
  { kind: 'text', text: '改用 --cd 重新派发。' },
  { kind: 'tool', tool: { name: 'Bash', summary: 'codex', input: {}, diffs: [] } },
  { kind: 'text', text: '已经修好了。' }
])
if (grouped.probes.length !== 2) {
  throw new Error(`expected 2 probes, got ${grouped.probes.length}`)
}
if (!grouped.probes[0]?.title.includes('核验') || grouped.probes[0].tools.length !== 2) {
  throw new Error('first probe should be working note + grep/read')
}
if (!grouped.probes[1]?.title.includes('重新派发') || grouped.probes[1].tools[0]?.name !== 'Bash') {
  throw new Error('second probe should be bash')
}
if (grouped.reply.join('') !== '已经修好了。') {
  throw new Error('trailing text should be the user-facing reply')
}
if (!hasAssistantWork(grouped)) {
  throw new Error('grouped work should count as assistant work')
}
const workLine = summarizeWork(grouped)
if (!workLine.includes('搜索') || !workLine.includes('读取') || !workLine.includes('执行')) {
  throw new Error(`bad work summary: ${workLine}`)
}

const injectedCases: { raw: string; ruleId: string }[] = [
  {
    raw: 'Perform any necessary follow-up actions to complete the task, then report back.',
    ruleId: 'follow-up'
  },
  { raw: '<system-reminder>\nPlan mode is active.\n</system-reminder>', ruleId: 'system-reminder' },
  { raw: '<local-command-stdout>ok</local-command-stdout>', ruleId: 'local-command' },
  {
    raw: 'Caveat: The messages below were generated by the user while running local commands.',
    ruleId: 'caveat'
  },
  { raw: '[Request interrupted by user]', ruleId: 'interrupted' },
  {
    raw: 'This session is being continued from a previous conversation that ran out of context.',
    ruleId: 'compact-continue'
  }
]
for (const { raw, ruleId } of injectedCases) {
  const classified = classifyUserText(raw)
  if (classified.kind !== 'injected' || classified.ruleId !== ruleId) {
    throw new Error(`expected ${ruleId} injection, got ${classified.kind}/${classified.ruleId ?? '-'}`)
  }
  if (!classified.label) throw new Error(`rule ${ruleId} must carry a label`)
}

// 保守边界：真实用户输入不能被吃掉，注入话术只在开头锚定时才算数
const userCases = [
  '把 operateTypeList 补上',
  '记得 perform any necessary follow-up actions 之后再回我',
  '这段 <system-reminder> 是什么意思？',
  'Caveat 这个词怎么翻译',
  'continue'
]
for (const raw of userCases) {
  const classified = classifyUserText(raw)
  if (classified.kind !== 'user') {
    throw new Error(`real user text misread as injection: ${raw} (${classified.ruleId ?? '-'})`)
  }
  if (classified.text !== raw.trim()) throw new Error(`user text should pass through: ${raw}`)
}

// 斜杠命令的既有归一化不能被 classifyUserText 破坏
const command = classifyUserText('<command-name>/review</command-name><command-args>HEAD</command-args>')
if (command.kind !== 'user' || !command.text.startsWith('命令 /review')) {
  throw new Error(`command normalization broken: ${command.kind} ${command.text}`)
}

const injectedMessages: Message[] = [
  {
    id: 'u-inject',
    conversationId: 'c2',
    seq: 0,
    role: 'user',
    createdAt: 1,
    parts: [{ kind: 'text', text: 'Perform any necessary follow-up actions and continue.' }]
  },
  {
    id: 'u-real',
    conversationId: 'c2',
    seq: 1,
    role: 'user',
    createdAt: 2,
    parts: [{ kind: 'text', text: '继续' }]
  }
]
const injectedItems = projectDialogue(injectedMessages)
const injectedTurn = injectedItems[0]
if (injectedTurn?.kind !== 'turn' || injectedTurn.role !== 'user') {
  throw new Error('injected user message should still produce a user turn')
}
const injected = injectionsOf(injectedTurn)
if (textsOf(injectedTurn).length !== 0 || injected.length !== 1 || !injected[0]?.label) {
  throw new Error('injected text should render as a labelled system-injection row, not a bubble')
}
const realTurn = injectedItems[1]
if (realTurn?.kind !== 'turn' || textsOf(realTurn)[0] !== '继续') {
  throw new Error('real user text should stay a bubble')
}

const dual: Message[] = [
  {
    id: 'u-dual',
    conversationId: 'c3',
    seq: 0,
    role: 'user',
    createdAt: 1,
    parts: [{ kind: 'text', text: '改两处' }]
  },
  {
    id: 'a-dual',
    conversationId: 'c3',
    seq: 1,
    role: 'assistant',
    createdAt: 2,
    parts: [
      { kind: 'tool_call', name: 'Read', callId: 'r1', input: { path: 'a.ts' } },
      { kind: 'tool_call', name: 'Read', callId: 'r2', input: { path: 'b.ts' } },
      { kind: 'diff', path: 'b.ts', patch: '+x' }
    ]
  },
  {
    id: 't-dual',
    conversationId: 'c3',
    seq: 2,
    role: 'tool',
    createdAt: 3,
    parts: [
      { kind: 'tool_result', callId: 'r2', output: 'bbb' },
      { kind: 'tool_result', callId: 'r1', output: 'aaa' }
    ]
  }
]
const dualItems = projectDialogue(dual)
const dualAssistant = dualItems.find((item) => item.kind === 'turn' && item.role === 'assistant')
if (!dualAssistant || dualAssistant.kind !== 'turn') throw new Error('dual assistant')
const dualTools = toolsOf(dualAssistant)
if (dualTools.length !== 2) throw new Error(`dual tools ${dualTools.length}`)
if (dualTools[0]?.output !== 'aaa' || dualTools[1]?.output !== 'bbb') {
  throw new Error('Map attach should match by callId, not reverse scan order')
}
if (dualTools[1]?.diffs[0]?.path !== 'b.ts') throw new Error('diff should attach to last tool')

console.log('ok: dialogue projects 5 raw messages → 1 exchange (user + probe + reply)')
console.log(`ok: classifyUserText 命中 ${injectedCases.length} 类注入，${userCases.length} 条真实输入原样保留`)
